In [20]:
from keras.preprocessing.text import Tokenizer
from sklearn.preprocessing import LabelEncoder
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [21]:
from keras.datasets import imdb
from keras.preprocessing import sequence

max_features = 10000  # number of words to consider as features
maxlen = 500  # cut texts after this number of words (among top max_features most common words)
batch_size = 32

print('Loading data...')
(input_train, y_train), (input_test, y_test) = imdb.load_data(num_words=max_features)
print(len(input_train), 'train sequences')
print(len(input_test), 'test sequences')

print('Pad sequences (samples x time)')
input_train = sequence.pad_sequences(input_train, maxlen=maxlen)
input_test = sequence.pad_sequences(input_test, maxlen=maxlen)
print('input_train shape:', input_train.shape)
print('input_test shape:', input_test.shape)

Loading data...
25000 train sequences
25000 test sequences
Pad sequences (samples x time)
input_train shape: (25000, 500)
input_test shape: (25000, 500)


In [22]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [23]:
from keras.layers import Dense, LSTM
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN
max_review_length = 500
model = Sequential()
model.add(Embedding(max_features, 16, input_length=max_review_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(input_train, y_train,
                    epochs=5,
                    batch_size=64,
                    validation_data=(input_test,y_test))

Train on 25000 samples, validate on 25000 samples
Epoch 1/5
25000/25000 [==============================] - 243s 10ms/step - loss: 0.4767 - acc: 0.7688 - val_loss: 0.3527 - val_acc: 0.8522
Epoch 2/5
25000/25000 [==============================] - 200s 8ms/step - loss: 0.2867 - acc: 0.8845 - val_loss: 0.3219 - val_acc: 0.8704
Epoch 3/5
25000/25000 [==============================] - 204s 8ms/step - loss: 0.2156 - acc: 0.9181 - val_loss: 0.3308 - val_acc: 0.8579
Epoch 4/5
25000/25000 [==============================] - 212s 8ms/step - loss: 0.1943 - acc: 0.9276 - val_loss: 0.3503 - val_acc: 0.8564
Epoch 5/5
25000/25000 [==============================] - 889s 36ms/step - loss: 0.1494 - acc: 0.9474 - val_loss: 0.3491 - val_acc: 0.8642


In [3]:
import json
import numpy as np
import pandas as pd

In [4]:
microsoft = pd.read_json('microsoft.json')
microsoft.shape

(152, 2)

In [5]:
google = pd.read_json('google_call_earnings.json')
google.shape

(138, 2)

In [6]:
facebook = pd.read_json('FB_earnings_call_transcript.json')
facebook.shape

(157, 2)

In [7]:
amazon = pd.read_json('Amazon_Q3_2018_Earning_Call_Transcript_Sentiment_Manual.json')
amazon.shape

(77, 2)

In [8]:
netflix = pd.read_json('NETFLIX_Q3_2018_EARNINGS_CALL_TRANSCRIPT_FANG.json')
netflix.shape

(98, 2)

In [9]:
data =pd.concat([microsoft, google , netflix , facebook, amazon], axis = 0)
data = data.sample(frac=1)
data = data.apply(lambda x: x.str.lower() if(x.dtype == 'object') else x)
data.head()

text sentiment
57  rate came in at 14% due to a benefit from an r...  positive
1   greetings and welcome to the microsoft fiscal ...  positive
49  investment in sales capacity and cloud enginee...  positive
7   last quarter, for the first time, we also shar...  positive
54  than expected software and services revenue.we...  positive

False    379
True     243
Name: sentiment, dtype: int64

In [10]:
X = data['text'].values
X


array(["rate came in at 14% due to a benefit from an r&d tax credit.we returned $6.3 billion to shareholders through dividends and share repurchases, increasing total shareholder return by 37%. we nearly doubled our year-over-year amount buyback, accelerating our pace from the prior quarter and now have roughly $30 billion remaining of our current $40 billion share repurchase authorization.now let's turn",
       'greetings and welcome to the microsoft fiscal year 2018 third quarter earnings conference call. as a reminder, this conference is being recorded. it is now my pleasure to introduce your host, mike spencer, general manager of investor relations. thank you. you may begin.michael spencer - microsoft corp.good afternoon and thank you for joining us today. on the call with me are satya nadella, chief',
       'investment in sales capacity and cloud engineering. operating income increased 24%, up 21% in constant currency.now to the results of more personal computing. revenue from t

In [124]:
y = data['sentiment'].values
y

array(['neutral', 'positive', 'positive', 'positive', 'negative',
       'positive', 'positive', 'neutral', 'neutral', 'negative',
       'negative', 'positive', 'negative', 'positive', 'positive',
       'positive', 'neutral', 'positive', 'neutral', 'neutral',
       'positive', 'positive', 'positive', 'positive', 'neutral',
       'positive', 'negative', 'negative', 'neutral', 'positive',
       'positive', 'positive', 'neutral', 'positive', 'neutral',
       'negative', 'neutral', 'neutral', 'neutral', 'neutral', 'positive',
       'positive', 'positive', 'positive', 'neutral', 'neutral',
       'positive', 'positive', 'negative', 'positive', 'negative',
       'neutral', 'positive', 'neutral', 'positive', 'neutral',
       'positive', 'positive', 'positive', 'positive', 'neutral',
       'neutral', 'neutral', 'negative', 'positive', 'positive',
       'neutral', 'neutral', 'positive', 'neutral', 'positive',
       'positive', 'positive', 'negative', 'positive', 'neutral',
       'p

In [11]:
y = data.sentiment.map({'positive':1, 'neutral':1, 'negative':0})
np.unique(y)


array([0, 1])

In [12]:
X

array(["rate came in at 14% due to a benefit from an r&d tax credit.we returned $6.3 billion to shareholders through dividends and share repurchases, increasing total shareholder return by 37%. we nearly doubled our year-over-year amount buyback, accelerating our pace from the prior quarter and now have roughly $30 billion remaining of our current $40 billion share repurchase authorization.now let's turn",
       'greetings and welcome to the microsoft fiscal year 2018 third quarter earnings conference call. as a reminder, this conference is being recorded. it is now my pleasure to introduce your host, mike spencer, general manager of investor relations. thank you. you may begin.michael spencer - microsoft corp.good afternoon and thank you for joining us today. on the call with me are satya nadella, chief',
       'investment in sales capacity and cloud engineering. operating income increased 24%, up 21% in constant currency.now to the results of more personal computing. revenue from t

In [ ]:
y

In [18]:
scores = model.evaluate(X, y, verbose=0)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))



NameError: name 'model' is not defined

In [15]:
tokenizer = Tokenizer(num_words=None, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~ ', lower=True, split=' ')
tokenizer.fit_on_texts(X)
X = tokenizer.texts_to_sequences(X)
X = pad_sequences(X, maxlen=400, padding='post')


In [16]:
X

array([[ 146,  561,    5, ...,    0,    0,    0],
       [2242,    2,  671, ...,    0,    0,    0],
       [ 236,    5,  272, ...,    0,    0,    0],
       ...,
       [ 537,  124,  146, ...,    0,    0,    0],
       [   4,  627,    7, ...,    0,    0,    0],
       [ 139,  273,   54, ...,    0,    0,    0]], dtype=int32)

In [17]:

pre_cls = model.predict_classes(X)
pre_cls
cm1 = confusion_matrix(y,pre_cls)
print('Confusion Matrix : \n', cm1)
pre_cls

NameError: name 'model' is not defined

acc: 90.03%


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [106]:
# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y, y_pred)
cm

array([[  0,  62],
       [  0, 560]])

In [95]:
model = Sequential()
model.add(Embedding(max_features, 32))
model.add(SimpleRNN(64))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(input_train, y_train,
                    epochs=10,
                    batch_size=128,
                    validation_data=(X,y))

NameError: name 'Dropout' is not defined

In [69]:
from keras.layers import LSTM

model = Sequential()
model.add(Embedding(max_features, 32))
model.add(LSTM(32))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['acc'])
history = model.fit(input_train, y_train,
                    epochs=10,
                    batch_size=128,
                    validation_data=(X,y))

Train on 25000 samples, validate on 622 samples
Epoch 1/10
25000/25000 [==============================] - 81s 3ms/step - loss: 0.4722 - acc: 0.7748 - val_loss: 0.5607 - val_acc: 0.9003
Epoch 2/10
25000/25000 [==============================] - 82s 3ms/step - loss: 0.2743 - acc: 0.8921 - val_loss: 0.4976 - val_acc: 0.9003
Epoch 3/10
25000/25000 [==============================] - 81s 3ms/step - loss: 0.2308 - acc: 0.9110 - val_loss: 0.7103 - val_acc: 0.0997
Epoch 4/10
25000/25000 [==============================] - 80s 3ms/step - loss: 0.1957 - acc: 0.9270 - val_loss: 0.5967 - val_acc: 0.9003
Epoch 5/10
25000/25000 [==============================] - 88s 4ms/step - loss: 0.1821 - acc: 0.9318 - val_loss: 0.7770 - val_acc: 0.0997
Epoch 6/10
25000/25000 [==============================] - 118s 5ms/step - loss: 0.1640 - acc: 0.9401 - val_loss: 0.6287 - val_acc: 0.9003
Epoch 7/10
25000/25000 [==============================] - 161s 6ms/step - loss: 0.1489 - acc: 0.9484 - val_loss: 0.6903 - val_acc